export * from "./mainpage"
export * from "./mainpage/aboutDcg";
export * from "./mainpage/levelMemebership";
export * from "./mainpage/team";
export * from "./mainpage/mintpasses";
export * from "./mainpage/projects";
export * from "./mainpage/contactus";
export * from "./privacypage";
export * from "./term&services";
export * from "./refundpolicy";